### ISSUE TITLE
Why async/await cause BC impact?

### ISSUE THREAD

**Issue by sj-i** [fiberphp/fiber-ext#31]
Related to #10 .
The RFC states it doesn't introduce async/await, but some people want them though.
Maybe the RFC needs more explanation for the people, because changes to language needs 2/3+1 majority.

## Are async/await really break BC?
IIRC, async/await were initially introduced in C#.
Especially for async, one of the reason it was introduced is to keep backward compatibility.
When 'async' is used in a function signature, that means the function is not made before async/await are introduced, 'await' can be safely a keyword in this context.
Consider the situation there is 'await' only and no 'async'.

```await +3;```

There is ambiguity in this code. It can be read as a expression consists of
 - a constant named 'await',
 - a binary operator '+',
 - and a literal integer value '3'.

So C# introduced another keyword, async.

```
async function f() { await +3;}
```

There is no ambiguity in this code. 'await' can be  safely read as a keyword because of the existence of 'async'.  The case of ```await(somthing);``` can be also solved.

Then again, why async/await cause BC break in PHP? 
What code will be broken in PHP actually.
If they break no code, I think the RFC needs another reason not to implement them (for now) or another choice.

**Comment by joelwurtz** [comment]
If we compare to other language that have `async` keyword, there is another class to add, in fact in C# or in Javascript having a function `async` means we have to return a Promise or Task in this function.

And IMO this RFC is not about promise or task, it's about pausing / resuming a PHP VM. And if we compare to other languages this concept is a lot more related to LUA coroutine which does not provide async or await, as there are not needed.

In #10 Fiber was the Promise / Task object, but it miss a lot of thing : There is no wait method, there is no global event loop / scheduler preventing that some fiber are never executed, and certainly other thing that i miss.

Adding those keywords would then add a lot of complexity to this RFC and too many decisions to take, and IMO the right approach should be one step at a time.

> Then again, why async/await cause BC break in PHP?

It does not, however existing async lib (react / amp / ...) would then use those keywords which whould then breaks existing projects using those libs (but it that really a problem ?)

**Comment by martinschroeder** [comment]
I fully agree with @joelwurtz on the scope of this RFC. Fibers are not related to `async` / `await`, they are just a means of having interruptable functions that are scheduled by userland code. I would love to see `async` & `await` in another RFC in the future if fibers do make it to the core of PHP.

It is worth noting that the way `async` is implemented in other languages (C#, Python, JavaScript) is not the best solution if you are using native fibers. Adding the `async` keyword to functions makes the "async execution model" part of the public API of that function which enforces programming "async all the way" and limits the usefulness of async functions a lot. I think Go offers a much better solution with it's goroutines. The basic idea is that the caller decides if a function is to be executed in an asynchronous way. This can easily be implemented in PHP if fibers are available:
```php
$task = async min(3, 1, 2);
$result = await $task;
```
This example shows how every function call can be turned into an async call by prepending the `async` keyword to it. Doing so would create an `AsyncTask` object instead of calling `min()` that stores the function to be called and the arguments to be passed to it. Using `await` will pause the current fiber and resume it when the async function finished execution. This is basically a very simple source transformation that would result in code like this:
```php
$task = new AsyncTask(Closure::fromCallable('min'), 3, 1, 2);
$result = Fiber::yield($task);
```
The code transformation uses `Closure::fromCallable()` to preserve the calling scope in case of calls to protected or private methods within classes. You can have a look at an example implementation in https://github.com/martinschroeder/async-await (Note: is used functions `async()` and `await()` instead of keywords, but the general idea is the same).

**Comment by sj-i** [comment]
@joelwurtz 
> the right approach should be one step at a time.

Agreed.

> however existing async lib (react / amp / ...) would then use those keywords which whould then breaks existing projects using those libs (but it that really a problem ?)

It's not really a problem. Nothing will be automatically broken.

@martinschroeder 
> The basic idea is that the caller decides if a function is to be executed in an asynchronous way. 

Interesting.
Another care for BC impacts will be needed though.

Summary:
- If fibers will be in the core, some sweet syntax like async/await can be built on top of it.
- Introducing new keywords async/await in the same manner of C#/Javascript/Python itself breaks no BC.
- It's simply out of the scope of this RFC.

@lvht 
I suggest to remove mentions about async/await from the "Open Issues" section  in the RFC, and add statements like "syntax like async/await can be implemented in the future, but it's out of the scope of this RFC." to the "Future Scope" section. 
So this RFC could be supported by people they want something like async/await in futere version of PHP.

https://wiki.php.net/rfc/fiber#open_issues
https://wiki.php.net/rfc/fiber#future_scope

**Comment by lvht** [comment]
@sj-i updated.

**Comment by sj-i** [comment]
@lvht Thanks!
